### ISSUE TITLE
savedefault debe resperata /etc/default/grub

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/huayra-partition-tools#1]
Mauro, cambié hace unos dias en 451055688cc06ba34c2525846d002d481f09190c que tenga la opcion savedefault cada uno de los items en el template que se agregan.

Pero esta funcionalidad debería depender si se usa o no (y del valor de) GRUB_SAVEDEFAULT en /etc/default/grub

Hay que modificar el script para que dependiendo de esa variable, los agregue o no.
Yo creo que en el contexto que se ejecuta el script dede /etc/grub.d ya podés leer esa variable directamente desde el entorno, como lo hace por ejemplo 30_os-prober:

<pre>
if [ "x${GRUB_DISABLE_OS_PROBER}" = "xtrue" ]; then
  exit 0
fi
</pre>

**Comment by lvm** [comment]
Lo que entiendo como mas práctico para este caso es simplemente definir las variables

```
GRUB_DEFAULT=saved
GRUB_SAVEDEFAULT=true
```

en `/etc/default/grub` y ya. No veo la necesidad de que sea variable la existencia de `savedefault`, si está deshabilitado simplemente no la va a tomar en cuenta.

**Comment by lvm** [comment]
ver commit 155fd7fe2d3aa4268fbbfcaae5bd3d6d44e63d92
